name: tunnel_tracker
description: Tunnel Tracking System - Worker Registration App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase - Latest compatible versions
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  
  # State Management
  provider: ^6.1.1
  
  # UI & Theming
  material_symbols_icons: ^4.2762.0
  flutter_launcher_icons: ^0.13.1
  
  # Networking & Utilities
  http: ^1.1.0
  connectivity_plus: ^5.0.2
  
  # Device Info & MAC Detection
  device_info_plus: ^11.5.0
  network_info_plus: ^6.1.4
  permission_handler: ^12.0.1
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Utilities
  uuid: ^4.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png" 